### ISSUE TITLE
文档内部链接应跳转到中文链接

### ISSUE THREAD

**Issue by tdzl2003** [reactnativecn/react-native-docs-cn#3]
#2  这个pull request引入了一些文档内部的链接，但没有跳转到对应的中文版本，而是跳转到了英文版本。

http://react-native.cn/docs/communication-ios.html#content

标题和跳转地址都应该是中文版本

**Comment by tdzl2003** [comment]
另外还有多余的头部文字需要去掉

**Comment by sunnylqm** [comment]
这个我来修订
