### ISSUE TITLE
网站的 css 挂掉了

### ISSUE THREAD

**Issue by binyu1231** [reactnativecn/react-native-docs-cn#44]
报错是 `Uncaught Error: Cannot find module "bootstrap/less/bootstrap.less"`

**Comment by sunnylqm** [comment]
正在处理

**Comment by binyu1231** [comment]
辛苦了😄

**Comment by sunnylqm** [comment]
less2.7版本的bug  https://github.com/less/less.js/issues/2896
已回滚修复 https://github.com/reactnativecn/react-native.cn/pull/31
