### ISSUE TITLE
官网更新

### ISSUE THREAD

**Issue by MessyPaste** [reactnativecn/react-native-docs-cn#49]
我最近看官网http://facebook.github.io/react-native/docs/embedded-app-android.html#content
将react集成至现有的Android安卓项目，发现官网还是0.20.+，但是最新版本已经到0.25.1了，我想用最新版本就用不了只有加载本地模块，所以出现这么一个问题：当官网的内容已经过时的时候，我们cn的站点是以保持同步为准呢还是新开一篇最新的教程？

**Comment by sunnylqm** [comment]
文档目前主要是由我在维护。所以我只能修订我有把握的东西。原生方面我不懂，如果你了解这方面，建议先提交官方，然后我会跟进。当然你也可以PR给我们，我会让其他人review看看。

**Comment by sunnylqm** [comment]
已跟进官方最新修改  https://github.com/reactnativecn/react-native-docs-cn/commit/2b8a36dfb3c3d6faa713ac373be321979b900104
