### ISSUE TITLE
0.26 的 Modal 中的animated 已过时

### ISSUE THREAD

**Issue by cockhorseman** [reactnativecn/react-native-docs-cn#57]
使用animationType enum('none', 'slide', 'fade') 代替
[中文网](http://reactnative.cn/docs/0.26/modal.html#content)

` getInitialState() {
    return {
      animated: true,
      modalVisible: false,
      transparent: false,
    };
  },`

`_toggleAnimated() {
    this.setState({animated: !this.state.animated});
  },`
的事例代码未更新
[英文网](https://facebook.github.io/react-native/docs/modal.html#content)

` getInitialState() {
    return {
      animationType: 'none',
      modalVisible: false,
      transparent: false,
    };
  },`

` _setAnimationType(type) {
    this.setState({animationType: type});
  },`

**Comment by sunnylqm** [comment]
已添加
