### ISSUE TITLE
Model  属性中的  animationType解释应在animated位置上

### ISSUE THREAD

**Issue by cockhorseman** [reactnativecn/react-native-docs-cn#58]
`
animated bool 

animationType enum('none', 'slide', 'fade') 

已过期
请使用animationType 属性代替。
`

应该是：
`animated bool 
已过期
请使用animationType 属性代替。`
animationType enum('none', 'slide', 'fade')

**Comment by sunnylqm** [comment]
汗。。。稍后修改
