### ISSUE TITLE
0.27 animations 翻译不完整

### ISSUE THREAD

**Issue by sudosiyang** [reactnativecn/react-native-docs-cn#66]

**Comment by sunnylqm** [comment]
具体？

**Comment by sudosiyang** [comment]
Note that in order to get this to work on Android you need to set the following flags via UIManager:

UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);

**Comment by sunnylqm** [comment]
![qq 20160615101729](https://cloud.githubusercontent.com/assets/615282/16066022/6c02d726-32e2-11e6-989e-4fdf67de4a0c.png)

**Comment by sudosiyang** [comment]
ok，我看错地方了😂
